//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Файл {
    
    private ФайлДокумент документField;
    
    private string идФайлField;
    
    private string версПрогField;
    
    private ФайлВерсФорм версФормField;
    
    /// <remarks/>
    public ФайлДокумент Документ {
        get {
            return this.документField;
        }
        set {
            this.документField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ИдФайл {
        get {
            return this.идФайлField;
        }
        set {
            this.идФайлField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ВерсПрог {
        get {
            return this.версПрогField;
        }
        set {
            this.версПрогField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлВерсФорм ВерсФорм {
        get {
            return this.версФормField;
        }
        set {
            this.версФормField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокумент {
    
    private ФайлДокументСвНП свНПField;
    
    private ФайлДокументПодписант подписантField;
    
    private ФайлДокументУведУчИО уведУчИОField;
    
    private ФайлДокументКНД кНДField;
    
    private string датаДокField;
    
    private string кодНОField;
    
    private string номКоррField;
    
    /// <remarks/>
    public ФайлДокументСвНП СвНП {
        get {
            return this.свНПField;
        }
        set {
            this.свНПField = value;
        }
    }
    
    /// <remarks/>
    public ФайлДокументПодписант Подписант {
        get {
            return this.подписантField;
        }
        set {
            this.подписантField = value;
        }
    }
    
    /// <remarks/>
    public ФайлДокументУведУчИО УведУчИО {
        get {
            return this.уведУчИОField;
        }
        set {
            this.уведУчИОField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументКНД КНД {
        get {
            return this.кНДField;
        }
        set {
            this.кНДField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ДатаДок {
        get {
            return this.датаДокField;
        }
        set {
            this.датаДокField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string КодНО {
        get {
            return this.кодНОField;
        }
        set {
            this.кодНОField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string НомКорр {
        get {
            return this.номКоррField;
        }
        set {
            this.номКоррField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументСвНП {
    
    private object itemField;
    
    private ФайлДокументСвНППрНП прНПField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("НПФЛ", typeof(ФайлДокументСвНПНПФЛ))]
    [System.Xml.Serialization.XmlElementAttribute("НПЮЛ", typeof(ФайлДокументСвНПНПЮЛ))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументСвНППрНП ПрНП {
        get {
            return this.прНПField;
        }
        set {
            this.прНПField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументСвНПНПФЛ {
    
    private ФИОТип фИОField;
    
    private ФайлДокументСвНПНПФЛСведФЛ сведФЛField;
    
    private string иННФЛField;
    
    /// <remarks/>
    public ФИОТип ФИО {
        get {
            return this.фИОField;
        }
        set {
            this.фИОField = value;
        }
    }
    
    /// <remarks/>
    public ФайлДокументСвНПНПФЛСведФЛ СведФЛ {
        get {
            return this.сведФЛField;
        }
        set {
            this.сведФЛField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ИННФЛ {
        get {
            return this.иННФЛField;
        }
        set {
            this.иННФЛField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ФИОТип {
    
    private string фамилияField;
    
    private string имяField;
    
    private string отчествоField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Фамилия {
        get {
            return this.фамилияField;
        }
        set {
            this.фамилияField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Имя {
        get {
            return this.имяField;
        }
        set {
            this.имяField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Отчество {
        get {
            return this.отчествоField;
        }
        set {
            this.отчествоField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class АдрРФТип {
    
    private string индексField;
    
    private string кодРегионField;
    
    private string районField;
    
    private string городField;
    
    private string населПунктField;
    
    private string улицаField;
    
    private string домField;
    
    private string корпусField;
    
    private string квартField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Индекс {
        get {
            return this.индексField;
        }
        set {
            this.индексField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string КодРегион {
        get {
            return this.кодРегионField;
        }
        set {
            this.кодРегионField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Район {
        get {
            return this.районField;
        }
        set {
            this.районField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Город {
        get {
            return this.городField;
        }
        set {
            this.городField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаселПункт {
        get {
            return this.населПунктField;
        }
        set {
            this.населПунктField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Улица {
        get {
            return this.улицаField;
        }
        set {
            this.улицаField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Дом {
        get {
            return this.домField;
        }
        set {
            this.домField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Корпус {
        get {
            return this.корпусField;
        }
        set {
            this.корпусField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Кварт {
        get {
            return this.квартField;
        }
        set {
            this.квартField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class УдЛичнФЛТип {
    
    private string кодВидДокField;
    
    private string серНомДокField;
    
    private string датаДокField;
    
    private string выдДокField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string КодВидДок {
        get {
            return this.кодВидДокField;
        }
        set {
            this.кодВидДокField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string СерНомДок {
        get {
            return this.серНомДокField;
        }
        set {
            this.серНомДокField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ДатаДок {
        get {
            return this.датаДокField;
        }
        set {
            this.датаДокField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ВыдДок {
        get {
            return this.выдДокField;
        }
        set {
            this.выдДокField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументСвНПНПФЛСведФЛ {
    
    private УдЛичнФЛТип удЛичнField;
    
    private УдЛичнФЛТип сведДокРегField;
    
    private ФайлДокументСвНПНПФЛСведФЛСвАдрРФ свАдрРФField;
    
    private ФайлДокументСвНПНПФЛСведФЛСвАдрИно свАдрИноField;
    
    private ФайлДокументСвНПНПФЛСведФЛПол полField;
    
    private string датаРождField;
    
    private string местоРождField;
    
    private ФайлДокументСвНПНПФЛСведФЛПрГражд прГраждField;
    
    private string оКСМField;
    
    /// <remarks/>
    public УдЛичнФЛТип УдЛичн {
        get {
            return this.удЛичнField;
        }
        set {
            this.удЛичнField = value;
        }
    }
    
    /// <remarks/>
    public УдЛичнФЛТип СведДокРег {
        get {
            return this.сведДокРегField;
        }
        set {
            this.сведДокРегField = value;
        }
    }
    
    /// <remarks/>
    public ФайлДокументСвНПНПФЛСведФЛСвАдрРФ СвАдрРФ {
        get {
            return this.свАдрРФField;
        }
        set {
            this.свАдрРФField = value;
        }
    }
    
    /// <remarks/>
    public ФайлДокументСвНПНПФЛСведФЛСвАдрИно СвАдрИно {
        get {
            return this.свАдрИноField;
        }
        set {
            this.свАдрИноField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументСвНПНПФЛСведФЛПол Пол {
        get {
            return this.полField;
        }
        set {
            this.полField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ДатаРожд {
        get {
            return this.датаРождField;
        }
        set {
            this.датаРождField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string МестоРожд {
        get {
            return this.местоРождField;
        }
        set {
            this.местоРождField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументСвНПНПФЛСведФЛПрГражд ПрГражд {
        get {
            return this.прГраждField;
        }
        set {
            this.прГраждField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ОКСМ {
        get {
            return this.оКСМField;
        }
        set {
            this.оКСМField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументСвНПНПФЛСведФЛСвАдрРФ {
    
    private АдрРФТип адрРФField;
    
    private ФайлДокументСвНПНПФЛСведФЛСвАдрРФПрАдр прАдрField;
    
    /// <remarks/>
    public АдрРФТип АдрРФ {
        get {
            return this.адрРФField;
        }
        set {
            this.адрРФField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументСвНПНПФЛСведФЛСвАдрРФПрАдр ПрАдр {
        get {
            return this.прАдрField;
        }
        set {
            this.прАдрField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументСвНПНПФЛСведФЛСвАдрРФПрАдр {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументСвНПНПФЛСведФЛСвАдрИно {
    
    private string оКСМField;
    
    private string адрИноField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ОКСМ {
        get {
            return this.оКСМField;
        }
        set {
            this.оКСМField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string АдрИно {
        get {
            return this.адрИноField;
        }
        set {
            this.адрИноField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументСвНПНПФЛСведФЛПол {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументСвНПНПФЛСведФЛПрГражд {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументСвНПНПЮЛ {
    
    private string наимОргField;
    
    private string иННЮЛField;
    
    private string кППField;
    
    private string оГРНField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаимОрг {
        get {
            return this.наимОргField;
        }
        set {
            this.наимОргField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ИННЮЛ {
        get {
            return this.иННЮЛField;
        }
        set {
            this.иННЮЛField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string КПП {
        get {
            return this.кППField;
        }
        set {
            this.кППField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ОГРН {
        get {
            return this.оГРНField;
        }
        set {
            this.оГРНField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументСвНППрНП {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументПодписант {
    
    private ФИОТип фИОField;
    
    private ФайлДокументПодписантСвПред свПредField;
    
    private ФайлДокументПодписантПрПодп прПодпField;
    
    private string иННФЛField;
    
    private string тлфField;
    
    private string emailField;
    
    /// <remarks/>
    public ФИОТип ФИО {
        get {
            return this.фИОField;
        }
        set {
            this.фИОField = value;
        }
    }
    
    /// <remarks/>
    public ФайлДокументПодписантСвПред СвПред {
        get {
            return this.свПредField;
        }
        set {
            this.свПредField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументПодписантПрПодп ПрПодп {
        get {
            return this.прПодпField;
        }
        set {
            this.прПодпField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ИННФЛ {
        get {
            return this.иННФЛField;
        }
        set {
            this.иННФЛField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Тлф {
        get {
            return this.тлфField;
        }
        set {
            this.тлфField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("E-mail")]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументПодписантСвПред {
    
    private string наимДокField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаимДок {
        get {
            return this.наимДокField;
        }
        set {
            this.наимДокField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументПодписантПрПодп {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументУведУчИО {
    
    private ФайлДокументУведУчИОСведИО[] сведИОField;
    
    private ФайлДокументУведУчИОСведРос[] сведРосField;
    
    private ФайлДокументУведУчИОСведИСБезЮЛ[] сведИСБезЮЛField;
    
    private ФайлДокументУведУчИОРаскрУчИОКосв[] раскрУчИОКосвField;
    
    private ФайлДокументУведУчИООснУвед оснУведField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("СведИО")]
    public ФайлДокументУведУчИОСведИО[] СведИО {
        get {
            return this.сведИОField;
        }
        set {
            this.сведИОField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("СведРос")]
    public ФайлДокументУведУчИОСведРос[] СведРос {
        get {
            return this.сведРосField;
        }
        set {
            this.сведРосField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("СведИСБезЮЛ")]
    public ФайлДокументУведУчИОСведИСБезЮЛ[] СведИСБезЮЛ {
        get {
            return this.сведИСБезЮЛField;
        }
        set {
            this.сведИСБезЮЛField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("РаскрУчИОКосв")]
    public ФайлДокументУведУчИОРаскрУчИОКосв[] РаскрУчИОКосв {
        get {
            return this.раскрУчИОКосвField;
        }
        set {
            this.раскрУчИОКосвField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументУведУчИООснУвед ОснУвед {
        get {
            return this.оснУведField;
        }
        set {
            this.оснУведField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументУведУчИОСведИО {
    
    private string номерИОField;
    
    private string наимОргField;
    
    private string наимОргЛатField;
    
    private string стрРегField;
    
    private string регНомерField;
    
    private string кодНПРегField;
    
    private string адрСтрРегField;
    
    private ФайлДокументУведУчИОСведИОУчастие участиеField;
    
    private string датаВознУчField;
    
    private decimal доляУчField;
    
    private string датаКонУчField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НомерИО {
        get {
            return this.номерИОField;
        }
        set {
            this.номерИОField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаимОрг {
        get {
            return this.наимОргField;
        }
        set {
            this.наимОргField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаимОргЛат {
        get {
            return this.наимОргЛатField;
        }
        set {
            this.наимОргЛатField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string СтрРег {
        get {
            return this.стрРегField;
        }
        set {
            this.стрРегField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string РегНомер {
        get {
            return this.регНомерField;
        }
        set {
            this.регНомерField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string КодНПРег {
        get {
            return this.кодНПРегField;
        }
        set {
            this.кодНПРегField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string АдрСтрРег {
        get {
            return this.адрСтрРегField;
        }
        set {
            this.адрСтрРегField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументУведУчИОСведИОУчастие Участие {
        get {
            return this.участиеField;
        }
        set {
            this.участиеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ДатаВознУч {
        get {
            return this.датаВознУчField;
        }
        set {
            this.датаВознУчField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal ДоляУч {
        get {
            return this.доляУчField;
        }
        set {
            this.доляУчField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ДатаКонУч {
        get {
            return this.датаКонУчField;
        }
        set {
            this.датаКонУчField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументУведУчИОСведИОУчастие {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументУведУчИОСведРос {
    
    private string номерРОField;
    
    private string наимОргField;
    
    private string оГРНField;
    
    private string иННЮЛField;
    
    private string кППField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НомерРО {
        get {
            return this.номерРОField;
        }
        set {
            this.номерРОField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаимОрг {
        get {
            return this.наимОргField;
        }
        set {
            this.наимОргField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ОГРН {
        get {
            return this.оГРНField;
        }
        set {
            this.оГРНField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ИННЮЛ {
        get {
            return this.иННЮЛField;
        }
        set {
            this.иННЮЛField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string КПП {
        get {
            return this.кППField;
        }
        set {
            this.кППField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументУведУчИОСведИСБезЮЛ {
    
    private ФайлДокументУведУчИОСведИСБезЮЛСведИС сведИСField;
    
    private string номерИСField;
    
    /// <remarks/>
    public ФайлДокументУведУчИОСведИСБезЮЛСведИС СведИС {
        get {
            return this.сведИСField;
        }
        set {
            this.сведИСField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НомерИС {
        get {
            return this.номерИСField;
        }
        set {
            this.номерИСField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументУведУчИОСведИСБезЮЛСведИС {
    
    private ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИС[] сведУчИСField;
    
    private ФайлДокументУведУчИОСведИСБезЮЛСведИСОргФорм оргФормField;
    
    private string наимОргField;
    
    private string наимОргЛатField;
    
    private string наимДокУчрField;
    
    private string наимДокУчрЛатField;
    
    private string датаУчрField;
    
    private string странаУчрИСField;
    
    private string регНомерИСField;
    
    private string иныеСведИСField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("СведУчИС")]
    public ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИС[] СведУчИС {
        get {
            return this.сведУчИСField;
        }
        set {
            this.сведУчИСField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументУведУчИОСведИСБезЮЛСведИСОргФорм ОргФорм {
        get {
            return this.оргФормField;
        }
        set {
            this.оргФормField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаимОрг {
        get {
            return this.наимОргField;
        }
        set {
            this.наимОргField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаимОргЛат {
        get {
            return this.наимОргЛатField;
        }
        set {
            this.наимОргЛатField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаимДокУчр {
        get {
            return this.наимДокУчрField;
        }
        set {
            this.наимДокУчрField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаимДокУчрЛат {
        get {
            return this.наимДокУчрЛатField;
        }
        set {
            this.наимДокУчрЛатField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ДатаУчр {
        get {
            return this.датаУчрField;
        }
        set {
            this.датаУчрField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string СтранаУчрИС {
        get {
            return this.странаУчрИСField;
        }
        set {
            this.странаУчрИСField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string РегНомерИС {
        get {
            return this.регНомерИСField;
        }
        set {
            this.регНомерИСField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ИныеСведИС {
        get {
            return this.иныеСведИСField;
        }
        set {
            this.иныеСведИСField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИС {
    
    private ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСОснУчред оснУчредField;
    
    private ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСОснОсущКонтр оснОсущКонтрField;
    
    private ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСОснПравДоход оснПравДоходField;
    
    private string статУчастField;
    
    private string статУчастЛатField;
    
    private string докОснКонтрField;
    
    private string описОснКонтрField;
    
    private ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСУчастИС участИСField;
    
    private string датаВознУчастField;
    
    private decimal доляУчастField;
    
    private bool доляУчастFieldSpecified;
    
    private string датаКонУчастField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСОснУчред ОснУчред {
        get {
            return this.оснУчредField;
        }
        set {
            this.оснУчредField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСОснОсущКонтр ОснОсущКонтр {
        get {
            return this.оснОсущКонтрField;
        }
        set {
            this.оснОсущКонтрField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСОснПравДоход ОснПравДоход {
        get {
            return this.оснПравДоходField;
        }
        set {
            this.оснПравДоходField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string СтатУчаст {
        get {
            return this.статУчастField;
        }
        set {
            this.статУчастField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string СтатУчастЛат {
        get {
            return this.статУчастЛатField;
        }
        set {
            this.статУчастЛатField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ДокОснКонтр {
        get {
            return this.докОснКонтрField;
        }
        set {
            this.докОснКонтрField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ОписОснКонтр {
        get {
            return this.описОснКонтрField;
        }
        set {
            this.описОснКонтрField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСУчастИС УчастИС {
        get {
            return this.участИСField;
        }
        set {
            this.участИСField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ДатаВознУчаст {
        get {
            return this.датаВознУчастField;
        }
        set {
            this.датаВознУчастField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal ДоляУчаст {
        get {
            return this.доляУчастField;
        }
        set {
            this.доляУчастField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ДоляУчастSpecified {
        get {
            return this.доляУчастFieldSpecified;
        }
        set {
            this.доляУчастFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ДатаКонУчаст {
        get {
            return this.датаКонУчастField;
        }
        set {
            this.датаКонУчастField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСОснУчред {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСОснОсущКонтр {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСОснПравДоход {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументУведУчИОСведИСБезЮЛСведИССведУчИСУчастИС {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументУведУчИОСведИСБезЮЛСведИСОргФорм {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументУведУчИОРаскрУчИОКосв {
    
    private ФайлДокументУведУчИОРаскрУчИОКосвСвУчКосвИО свУчКосвИОField;
    
    private ФайлДокументУведУчИОРаскрУчИОКосвРаскрУчИО[] раскрУчИОField;
    
    /// <remarks/>
    public ФайлДокументУведУчИОРаскрУчИОКосвСвУчКосвИО СвУчКосвИО {
        get {
            return this.свУчКосвИОField;
        }
        set {
            this.свУчКосвИОField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("РаскрУчИО")]
    public ФайлДокументУведУчИОРаскрУчИОКосвРаскрУчИО[] РаскрУчИО {
        get {
            return this.раскрУчИОField;
        }
        set {
            this.раскрУчИОField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументУведУчИОРаскрУчИОКосвСвУчКосвИО {
    
    private string номерИОField;
    
    private string наимОргField;
    
    private decimal доляУчКосвИтField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НомерИО {
        get {
            return this.номерИОField;
        }
        set {
            this.номерИОField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НаимОрг {
        get {
            return this.наимОргField;
        }
        set {
            this.наимОргField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal ДоляУчКосвИт {
        get {
            return this.доляУчКосвИтField;
        }
        set {
            this.доляУчКосвИтField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументУведУчИОРаскрУчИОКосвРаскрУчИО {
    
    private ФайлДокументУведУчИОРаскрУчИОКосвРаскрУчИОСведУчПосл[] сведУчПослField;
    
    private string номерПослField;
    
    private decimal доляКосвПослИтField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("СведУчПосл")]
    public ФайлДокументУведУчИОРаскрУчИОКосвРаскрУчИОСведУчПосл[] СведУчПосл {
        get {
            return this.сведУчПослField;
        }
        set {
            this.сведУчПослField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НомерПосл {
        get {
            return this.номерПослField;
        }
        set {
            this.номерПослField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal ДоляКосвПослИт {
        get {
            return this.доляКосвПослИтField;
        }
        set {
            this.доляКосвПослИтField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ФайлДокументУведУчИОРаскрУчИОКосвРаскрУчИОСведУчПосл {
    
    private string номерУчField;
    
    private decimal доляУчПрямField;
    
    private bool доляУчПрямFieldSpecified;
    
    private decimal доляУчКосвField;
    
    private bool доляУчКосвFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string НомерУч {
        get {
            return this.номерУчField;
        }
        set {
            this.номерУчField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal ДоляУчПрям {
        get {
            return this.доляУчПрямField;
        }
        set {
            this.доляУчПрямField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ДоляУчПрямSpecified {
        get {
            return this.доляУчПрямFieldSpecified;
        }
        set {
            this.доляУчПрямFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal ДоляУчКосв {
        get {
            return this.доляУчКосвField;
        }
        set {
            this.доляУчКосвField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ДоляУчКосвSpecified {
        get {
            return this.доляУчКосвFieldSpecified;
        }
        set {
            this.доляУчКосвFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументУведУчИООснУвед {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлДокументКНД {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1120411")]
    Item1120411,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ФайлВерсФорм {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5.01")]
    Item501,
}
