//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace KPMG.WebKik.Models.NotificationOdKikXML

{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ФИО", Namespace = "", IsNullable = false)]
    public partial class ФИОТип
    {

        private string фамилияField;

        private string имяField;

        private string отчествоField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия
        {
            get
            {
                return this.фамилияField;
            }
            set
            {
                this.фамилияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя
        {
            get
            {
                return this.имяField;
            }
            set
            {
                this.имяField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество
        {
            get
            {
                return this.отчествоField;
            }
            set
            {
                this.отчествоField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрРФТип
    {

        private string индексField;

        private string кодРегионField;

        private string районField;

        private string городField;

        private string населПунктField;

        private string улицаField;

        private string домField;

        private string корпусField;

        private string квартField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс
        {
            get
            {
                return this.индексField;
            }
            set
            {
                this.индексField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодРегион
        {
            get
            {
                return this.кодРегионField;
            }
            set
            {
                this.кодРегионField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район
        {
            get
            {
                return this.районField;
            }
            set
            {
                this.районField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город
        {
            get
            {
                return this.городField;
            }
            set
            {
                this.городField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт
        {
            get
            {
                return this.населПунктField;
            }
            set
            {
                this.населПунктField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Улица
        {
            get
            {
                return this.улицаField;
            }
            set
            {
                this.улицаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Дом
        {
            get
            {
                return this.домField;
            }
            set
            {
                this.домField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Корпус
        {
            get
            {
                return this.корпусField;
            }
            set
            {
                this.корпусField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Кварт
        {
            get
            {
                return this.квартField;
            }
            set
            {
                this.квартField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class УдЛичнФЛТип
    {

        private string кодВидДокField;

        private string серНомДокField;

        private string датаДокField;

        private string выдДокField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодВидДок
        {
            get
            {
                return this.кодВидДокField;
            }
            set
            {
                this.кодВидДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СерНомДок
        {
            get
            {
                return this.серНомДокField;
            }
            set
            {
                this.серНомДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаДок
        {
            get
            {
                return this.датаДокField;
            }
            set
            {
                this.датаДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВыдДок
        {
            get
            {
                return this.выдДокField;
            }
            set
            {
                this.выдДокField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ОснПрНПКонтрКИК
    {

        private decimal код101Field;

        private decimal код102Field;

        private decimal код103Field;

        private decimal код104Field;

        private decimal код105Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код101
        {
            get
            {
                return this.код101Field;
            }
            set
            {
                this.код101Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код102
        {
            get
            {
                return this.код102Field;
            }
            set
            {
                this.код102Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код103
        {
            get
            {
                return this.код103Field;
            }
            set
            {
                this.код103Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код104
        {
            get
            {
                return this.код104Field;
            }
            set
            {
                this.код104Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код105
        {
            get
            {
                return this.код105Field;
            }
            set
            {
                this.код105Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Файл
    {

        private ФайлДокумент[] документField;

        private string идФайлField;

        private string версПрогField;

        private string версФормField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Документ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокумент[] Документ
        {
            get
            {
                return this.документField;
            }
            set
            {
                this.документField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл
        {
            get
            {
                return this.идФайлField;
            }
            set
            {
                this.идФайлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог
        {
            get
            {
                return this.версПрогField;
            }
            set
            {
                this.версПрогField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсФорм
        {
            get
            {
                return this.версФормField;
            }
            set
            {
                this.версФормField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокумент
    {

        private ФайлДокументСвНП[] свНПField;

        private ФайлДокументПодписант[] подписантField;

        private ФайлДокументУведУчКИК[] уведУчКИКField;

        private string кНДField;

        private string датаДокField;

        private string кодНОField;

        private string номКоррField;

        private string налПерField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвНП", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвНП[] СвНП
        {
            get
            {
                return this.свНПField;
            }
            set
            {
                this.свНПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Подписант", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументПодписант[] Подписант
        {
            get
            {
                return this.подписантField;
            }
            set
            {
                this.подписантField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("УведУчКИК", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИК[] УведУчКИК
        {
            get
            {
                return this.уведУчКИКField;
            }
            set
            {
                this.уведУчКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КНД
        {
            get
            {
                return this.кНДField;
            }
            set
            {
                this.кНДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаДок
        {
            get
            {
                return this.датаДокField;
            }
            set
            {
                this.датаДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодНО
        {
            get
            {
                return this.кодНОField;
            }
            set
            {
                this.кодНОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string НомКорр
        {
            get
            {
                return this.номКоррField;
            }
            set
            {
                this.номКоррField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "gYear")]
        public string НалПер
        {
            get
            {
                return this.налПерField;
            }
            set
            {
                this.налПерField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвНП
    {

        private ФайлДокументСвНПНПЮЛ[] нПЮЛField;

        private ФайлДокументСвНПНПФЛ[] нПФЛField;

        private decimal прНПField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НПЮЛ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвНПНПЮЛ[] НПЮЛ
        {
            get
            {
                return this.нПЮЛField;
            }
            set
            {
                this.нПЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НПФЛ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвНПНПФЛ[] НПФЛ
        {
            get
            {
                return this.нПФЛField;
            }
            set
            {
                this.нПФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ПрНП
        {
            get
            {
                return this.прНПField;
            }
            set
            {
                this.прНПField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвНПНПЮЛ
    {

        private string наимОргField;

        private string иННЮЛField;

        private string кППField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП
        {
            get
            {
                return this.кППField;
            }
            set
            {
                this.кППField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвНПНПФЛ
    {

        private string иННФЛField;

        private ФИОТип[] фИОField;

        private ФайлДокументСвНПНПФЛСведФЛ[] сведФЛField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ИННФЛ
        {
            get
            {
                return this.иННФЛField;
            }
            set
            {
                this.иННФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public ФИОТип[] ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведФЛ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвНПНПФЛСведФЛ[] СведФЛ
        {
            get
            {
                return this.сведФЛField;
            }
            set
            {
                this.сведФЛField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвНПНПФЛСведФЛ
    {

        private УдЛичнФЛТип[] удЛичнField;

        private УдЛичнФЛТип[] сведДокРегField;

        private ФайлДокументСвНПНПФЛСведФЛСвАдрРФ[] свАдрРФField;

        private ФайлДокументСвНПНПФЛСведФЛСвАдрИно[] свАдрИноField;

        private decimal полField;

        private string датаРождField;

        private string местоРождField;

        private decimal прГраждField;

        private string стрРегField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("УдЛичн", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УдЛичнФЛТип[] УдЛичн
        {
            get
            {
                return this.удЛичнField;
            }
            set
            {
                this.удЛичнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведДокРег", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УдЛичнФЛТип[] СведДокРег
        {
            get
            {
                return this.сведДокРегField;
            }
            set
            {
                this.сведДокРегField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвАдрРФ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвНПНПФЛСведФЛСвАдрРФ[] СвАдрРФ
        {
            get
            {
                return this.свАдрРФField;
            }
            set
            {
                this.свАдрРФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвАдрИно", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвНПНПФЛСведФЛСвАдрИно[] СвАдрИно
        {
            get
            {
                return this.свАдрИноField;
            }
            set
            {
                this.свАдрИноField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Пол
        {
            get
            {
                return this.полField;
            }
            set
            {
                this.полField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаРожд
        {
            get
            {
                return this.датаРождField;
            }
            set
            {
                this.датаРождField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string МестоРожд
        {
            get
            {
                return this.местоРождField;
            }
            set
            {
                this.местоРождField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ПрГражд
        {
            get
            {
                return this.прГраждField;
            }
            set
            {
                this.прГраждField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СтрРег
        {
            get
            {
                return this.стрРегField;
            }
            set
            {
                this.стрРегField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвНПНПФЛСведФЛСвАдрРФ
    {

        private АдрРФТип[] адрРФField;

        private decimal прАдрField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрРФ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public АдрРФТип[] АдрРФ
        {
            get
            {
                return this.адрРФField;
            }
            set
            {
                this.адрРФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ПрАдр
        {
            get
            {
                return this.прАдрField;
            }
            set
            {
                this.прАдрField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвНПНПФЛСведФЛСвАдрИно
    {

        private string оКСМField;

        private string адрИноField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКСМ
        {
            get
            {
                return this.оКСМField;
            }
            set
            {
                this.оКСМField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрИно
        {
            get
            {
                return this.адрИноField;
            }
            set
            {
                this.адрИноField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписант
    {

        private ФИОТип[] фИОField;

        private ФайлДокументПодписантСвПред[] свПредField;

        private string прПодпField;

        private string иННФЛField;

        private string тлфField;

        private string элАдресField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public ФИОТип[] ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПред", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументПодписантСвПред[] СвПред
        {
            get
            {
                return this.свПредField;
            }
            set
            {
                this.свПредField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПрПодп
        {
            get
            {
                return this.прПодпField;
            }
            set
            {
                this.прПодпField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get
            {
                return this.иННФЛField;
            }
            set
            {
                this.иННФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тлф
        {
            get
            {
                return this.тлфField;
            }
            set
            {
                this.тлфField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ЭлАдрес
        {
            get
            {
                return this.элАдресField;
            }
            set
            {
                this.элАдресField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписантСвПред
    {

        private string наимДокField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДок
        {
            get
            {
                return this.наимДокField;
            }
            set
            {
                this.наимДокField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИК
    {

        private ФайлДокументУведУчКИКСведКИКЯвлИО[] сведКИКЯвлИОField;

        private ФайлДокументУведУчКИКСведКИКЯвлИС[] сведКИКЯвлИСField;

        private ФайлДокументУведУчКИКСвФинОтчКИК[] свФинОтчКИКField;

        private ФайлДокументУведУчКИКРаскрУчКИККосв[] раскрУчКИККосвField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведКИКЯвлИО", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКСведКИКЯвлИО[] СведКИКЯвлИО
        {
            get
            {
                return this.сведКИКЯвлИОField;
            }
            set
            {
                this.сведКИКЯвлИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведКИКЯвлИС", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКСведКИКЯвлИС[] СведКИКЯвлИС
        {
            get
            {
                return this.сведКИКЯвлИСField;
            }
            set
            {
                this.сведКИКЯвлИСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвФинОтчКИК", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКСвФинОтчКИК[] СвФинОтчКИК
        {
            get
            {
                return this.свФинОтчКИКField;
            }
            set
            {
                this.свФинОтчКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("РаскрУчКИККосв", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКРаскрУчКИККосв[] РаскрУчКИККосв
        {
            get
            {
                return this.раскрУчКИККосвField;
            }
            set
            {
                this.раскрУчКИККосвField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКСведКИКЯвлИО
    {

        private ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИО[] оснПрНПКонтрКИКИОField;

        private string номерКИКField;

        private string наимОргField;

        private string наимОргЛатField;

        private string стрРегField;

        private string регНомерField;

        private string кодНПРегField;

        private string адрСтрРегField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОснПрНПКонтрКИКИО", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИО[] ОснПрНПКонтрКИКИО
        {
            get
            {
                return this.оснПрНПКонтрКИКИОField;
            }
            set
            {
                this.оснПрНПКонтрКИКИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерКИК
        {
            get
            {
                return this.номерКИКField;
            }
            set
            {
                this.номерКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОргЛат
        {
            get
            {
                return this.наимОргЛатField;
            }
            set
            {
                this.наимОргЛатField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СтрРег
        {
            get
            {
                return this.стрРегField;
            }
            set
            {
                this.стрРегField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РегНомер
        {
            get
            {
                return this.регНомерField;
            }
            set
            {
                this.регНомерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодНПРег
        {
            get
            {
                return this.кодНПРегField;
            }
            set
            {
                this.кодНПРегField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрСтрРег
        {
            get
            {
                return this.адрСтрРегField;
            }
            set
            {
                this.адрСтрРегField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИО
    {

        private ОснПрНПКонтрКИК[] оснПрНПКонтрКИКField;

        private ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИОСвУчКИК[] свУчКИКField;

        private ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИОСвКонтрКИК[] свКонтрКИКField;

        private string номерКИКField;

        private decimal прСамПризнField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОснПрНПКонтрКИК")]
        public ОснПрНПКонтрКИК[] ОснПрНПКонтрКИК
        {
            get
            {
                return this.оснПрНПКонтрКИКField;
            }
            set
            {
                this.оснПрНПКонтрКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвУчКИК", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИОСвУчКИК[] СвУчКИК
        {
            get
            {
                return this.свУчКИКField;
            }
            set
            {
                this.свУчКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвКонтрКИК", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИОСвКонтрКИК[] СвКонтрКИК
        {
            get
            {
                return this.свКонтрКИКField;
            }
            set
            {
                this.свКонтрКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерКИК
        {
            get
            {
                return this.номерКИКField;
            }
            set
            {
                this.номерКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ПрСамПризн
        {
            get
            {
                return this.прСамПризнField;
            }
            set
            {
                this.прСамПризнField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИОСвУчКИК
    {

        private ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИОСвУчКИКВидУч[] видУчField;

        private decimal доляПрямУчField;

        private bool доляПрямУчFieldSpecified;

        private decimal доляКосУчField;

        private bool доляКосУчFieldSpecified;

        private decimal доляСмешУчField;

        private bool доляСмешУчFieldSpecified;

        private decimal доляУчСупДетField;

        private bool доляУчСупДетFieldSpecified;

        private decimal доляУчНалРезРФField;

        private bool доляУчНалРезРФFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ВидУч", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИОСвУчКИКВидУч[] ВидУч
        {
            get
            {
                return this.видУчField;
            }
            set
            {
                this.видУчField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ДоляПрямУч
        {
            get
            {
                return this.доляПрямУчField;
            }
            set
            {
                this.доляПрямУчField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДоляПрямУчSpecified
        {
            get
            {
                return this.доляПрямУчFieldSpecified;
            }
            set
            {
                this.доляПрямУчFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ДоляКосУч
        {
            get
            {
                return this.доляКосУчField;
            }
            set
            {
                this.доляКосУчField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДоляКосУчSpecified
        {
            get
            {
                return this.доляКосУчFieldSpecified;
            }
            set
            {
                this.доляКосУчFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ДоляСмешУч
        {
            get
            {
                return this.доляСмешУчField;
            }
            set
            {
                this.доляСмешУчField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДоляСмешУчSpecified
        {
            get
            {
                return this.доляСмешУчFieldSpecified;
            }
            set
            {
                this.доляСмешУчFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ДоляУчСупДет
        {
            get
            {
                return this.доляУчСупДетField;
            }
            set
            {
                this.доляУчСупДетField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДоляУчСупДетSpecified
        {
            get
            {
                return this.доляУчСупДетFieldSpecified;
            }
            set
            {
                this.доляУчСупДетFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ДоляУчНалРезРФ
        {
            get
            {
                return this.доляУчНалРезРФField;
            }
            set
            {
                this.доляУчНалРезРФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДоляУчНалРезРФSpecified
        {
            get
            {
                return this.доляУчНалРезРФFieldSpecified;
            }
            set
            {
                this.доляУчНалРезРФFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИОСвУчКИКВидУч
    {

        private decimal код201Field;

        private decimal код202Field;

        private decimal код203Field;

        private decimal код204Field;

        private decimal код205Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код201
        {
            get
            {
                return this.код201Field;
            }
            set
            {
                this.код201Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код202
        {
            get
            {
                return this.код202Field;
            }
            set
            {
                this.код202Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код203
        {
            get
            {
                return this.код203Field;
            }
            set
            {
                this.код203Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код204
        {
            get
            {
                return this.код204Field;
            }
            set
            {
                this.код204Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код205
        {
            get
            {
                return this.код205Field;
            }
            set
            {
                this.код205Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКСведКИКЯвлИООснПрНПКонтрКИКИОСвКонтрКИК
    {

        private string оснКонтрИОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснКонтрИО
        {
            get
            {
                return this.оснКонтрИОField;
            }
            set
            {
                this.оснКонтрИОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКСведКИКЯвлИС
    {

        private ФайлДокументУведУчКИКСведКИКЯвлИСОснПрНПКонтрКИКИС[] оснПрНПКонтрКИКИСField;

        private string номерКИКField;

        private decimal оргФормField;

        private string наимОргField;

        private string наимОргЛатField;

        private string наимДокУчрField;

        private string наимДокУчрЛатField;

        private string датаУчрИСField;

        private string стрРегField;

        private string регНомерField;

        private string свИденИСField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОснПрНПКонтрКИКИС", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКСведКИКЯвлИСОснПрНПКонтрКИКИС[] ОснПрНПКонтрКИКИС
        {
            get
            {
                return this.оснПрНПКонтрКИКИСField;
            }
            set
            {
                this.оснПрНПКонтрКИКИСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерКИК
        {
            get
            {
                return this.номерКИКField;
            }
            set
            {
                this.номерКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ОргФорм
        {
            get
            {
                return this.оргФормField;
            }
            set
            {
                this.оргФормField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОргЛат
        {
            get
            {
                return this.наимОргЛатField;
            }
            set
            {
                this.наимОргЛатField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДокУчр
        {
            get
            {
                return this.наимДокУчрField;
            }
            set
            {
                this.наимДокУчрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДокУчрЛат
        {
            get
            {
                return this.наимДокУчрЛатField;
            }
            set
            {
                this.наимДокУчрЛатField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаУчрИС
        {
            get
            {
                return this.датаУчрИСField;
            }
            set
            {
                this.датаУчрИСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СтрРег
        {
            get
            {
                return this.стрРегField;
            }
            set
            {
                this.стрРегField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РегНомер
        {
            get
            {
                return this.регНомерField;
            }
            set
            {
                this.регНомерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвИденИС
        {
            get
            {
                return this.свИденИСField;
            }
            set
            {
                this.свИденИСField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКСведКИКЯвлИСОснПрНПКонтрКИКИС
    {

        private ОснПрНПКонтрКИК[] оснПрНПКонтрКИКField;

        private string номерКИКField;

        private decimal прСамПризнField;

        private string докИСField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОснПрНПКонтрКИК")]
        public ОснПрНПКонтрКИК[] ОснПрНПКонтрКИК
        {
            get
            {
                return this.оснПрНПКонтрКИКField;
            }
            set
            {
                this.оснПрНПКонтрКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерКИК
        {
            get
            {
                return this.номерКИКField;
            }
            set
            {
                this.номерКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ПрСамПризн
        {
            get
            {
                return this.прСамПризнField;
            }
            set
            {
                this.прСамПризнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДокИС
        {
            get
            {
                return this.докИСField;
            }
            set
            {
                this.докИСField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКСвФинОтчКИК
    {

        private ФайлДокументУведУчКИКСвФинОтчКИКОснОсвНОб[] оснОсвНОбField;

        private string номерКИКField;

        private decimal порОпрПрКИКField;

        private string датаПослДнПерField;

        private string датаСостФОField;

        private string датаПослДнПерГл25Field;

        private string датаСостАудЗаклField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОснОсвНОб", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКСвФинОтчКИКОснОсвНОб[] ОснОсвНОб
        {
            get
            {
                return this.оснОсвНОбField;
            }
            set
            {
                this.оснОсвНОбField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерКИК
        {
            get
            {
                return this.номерКИКField;
            }
            set
            {
                this.номерКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ПорОпрПрКИК
        {
            get
            {
                return this.порОпрПрКИКField;
            }
            set
            {
                this.порОпрПрКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПослДнПер
        {
            get
            {
                return this.датаПослДнПерField;
            }
            set
            {
                this.датаПослДнПерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаСостФО
        {
            get
            {
                return this.датаСостФОField;
            }
            set
            {
                this.датаСостФОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПослДнПерГл25
        {
            get
            {
                return this.датаПослДнПерГл25Field;
            }
            set
            {
                this.датаПослДнПерГл25Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаСостАудЗакл
        {
            get
            {
                return this.датаСостАудЗаклField;
            }
            set
            {
                this.датаСостАудЗаклField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКСвФинОтчКИКОснОсвНОб
    {

        private decimal код1001Field;

        private decimal код1002Field;

        private decimal код1003Field;

        private decimal код1004Field;

        private decimal код1005Field;

        private decimal код1006Field;

        private decimal код1007Field;

        private decimal код1008Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код1001
        {
            get
            {
                return this.код1001Field;
            }
            set
            {
                this.код1001Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код1002
        {
            get
            {
                return this.код1002Field;
            }
            set
            {
                this.код1002Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код1003
        {
            get
            {
                return this.код1003Field;
            }
            set
            {
                this.код1003Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код1004
        {
            get
            {
                return this.код1004Field;
            }
            set
            {
                this.код1004Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код1005
        {
            get
            {
                return this.код1005Field;
            }
            set
            {
                this.код1005Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код1006
        {
            get
            {
                return this.код1006Field;
            }
            set
            {
                this.код1006Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код1007
        {
            get
            {
                return this.код1007Field;
            }
            set
            {
                this.код1007Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Код1008
        {
            get
            {
                return this.код1008Field;
            }
            set
            {
                this.код1008Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКРаскрУчКИККосв
    {

        private ФайлДокументУведУчКИКРаскрУчКИККосвСвУчКосвКИК[] свУчКосвКИКField;

        private ФайлДокументУведУчКИКРаскрУчКИККосвРаскрУчКИК[] раскрУчКИКField;

        private ФайлДокументУведУчКИКРаскрУчКИККосвСвРосОрг[] свРосОргField;

        private ФайлДокументУведУчКИКРаскрУчКИККосвСвИО[] свИОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвУчКосвКИК", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКРаскрУчКИККосвСвУчКосвКИК[] СвУчКосвКИК
        {
            get
            {
                return this.свУчКосвКИКField;
            }
            set
            {
                this.свУчКосвКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("РаскрУчКИК", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКРаскрУчКИККосвРаскрУчКИК[] РаскрУчКИК
        {
            get
            {
                return this.раскрУчКИКField;
            }
            set
            {
                this.раскрУчКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвРосОрг", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКРаскрУчКИККосвСвРосОрг[] СвРосОрг
        {
            get
            {
                return this.свРосОргField;
            }
            set
            {
                this.свРосОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвИО", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКРаскрУчКИККосвСвИО[] СвИО
        {
            get
            {
                return this.свИОField;
            }
            set
            {
                this.свИОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКРаскрУчКИККосвСвУчКосвКИК
    {

        private string номерКИКField;

        private string наимОргField;

        private decimal доляУчКосвИтField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерКИК
        {
            get
            {
                return this.номерКИКField;
            }
            set
            {
                this.номерКИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ДоляУчКосвИт
        {
            get
            {
                return this.доляУчКосвИтField;
            }
            set
            {
                this.доляУчКосвИтField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКРаскрУчКИККосвРаскрУчКИК
    {

        private ФайлДокументУведУчКИКРаскрУчКИККосвРаскрУчКИКСведУчПосл[] сведУчПослField;

        private string номерПослField;

        private decimal доляКосвПослИтField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведУчПосл", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументУведУчКИКРаскрУчКИККосвРаскрУчКИКСведУчПосл[] СведУчПосл
        {
            get
            {
                return this.сведУчПослField;
            }
            set
            {
                this.сведУчПослField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерПосл
        {
            get
            {
                return this.номерПослField;
            }
            set
            {
                this.номерПослField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ДоляКосвПослИт
        {
            get
            {
                return this.доляКосвПослИтField;
            }
            set
            {
                this.доляКосвПослИтField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКРаскрУчКИККосвРаскрУчКИКСведУчПосл
    {

        private string номерУчField;

        private decimal доляУчПрямField;

        private bool доляУчПрямFieldSpecified;

        private decimal доляУчКосвField;

        private bool доляУчКосвFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерУч
        {
            get
            {
                return this.номерУчField;
            }
            set
            {
                this.номерУчField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ДоляУчПрям
        {
            get
            {
                return this.доляУчПрямField;
            }
            set
            {
                this.доляУчПрямField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДоляУчПрямSpecified
        {
            get
            {
                return this.доляУчПрямFieldSpecified;
            }
            set
            {
                this.доляУчПрямFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ДоляУчКосв
        {
            get
            {
                return this.доляУчКосвField;
            }
            set
            {
                this.доляУчКосвField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДоляУчКосвSpecified
        {
            get
            {
                return this.доляУчКосвFieldSpecified;
            }
            set
            {
                this.доляУчКосвFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКРаскрУчКИККосвСвРосОрг
    {

        private string номерРосОргField;

        private string оГРНField;

        private string иННЮЛField;

        private string кППField;

        private string наимОргField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерРосОрг
        {
            get
            {
                return this.номерРосОргField;
            }
            set
            {
                this.номерРосОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОГРН
        {
            get
            {
                return this.оГРНField;
            }
            set
            {
                this.оГРНField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП
        {
            get
            {
                return this.кППField;
            }
            set
            {
                this.кППField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУведУчКИКРаскрУчКИККосвСвИО
    {

        private string номерИОField;

        private string наимОргField;

        private string наимОргЛатField;

        private string стрРегField;

        private string регНомерField;

        private string кодНПРегField;

        private string адрСтрРегField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерИО
        {
            get
            {
                return this.номерИОField;
            }
            set
            {
                this.номерИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОргЛат
        {
            get
            {
                return this.наимОргЛатField;
            }
            set
            {
                this.наимОргЛатField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СтрРег
        {
            get
            {
                return this.стрРегField;
            }
            set
            {
                this.стрРегField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РегНомер
        {
            get
            {
                return this.регНомерField;
            }
            set
            {
                this.регНомерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодНПРег
        {
            get
            {
                return this.кодНПРегField;
            }
            set
            {
                this.кодНПРегField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрСтрРег
        {
            get
            {
                return this.адрСтрРегField;
            }
            set
            {
                this.адрСтрРегField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОснПрНПКонтрКИК", typeof(ОснПрНПКонтрКИК))]
        [System.Xml.Serialization.XmlElementAttribute("ФИО", typeof(ФИОТип))]
        [System.Xml.Serialization.XmlElementAttribute("Файл", typeof(Файл))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
